export function validateConfig(config) {
  if(!config||!Array.isArray(config.allowedOrigins)||!Array.isArray(config.apps))throw new Error('Capture config requires allowedOrigins and apps arrays.');
  if(!config.allowedOrigins.length)throw new Error('At least one exact origin must be approved.');
  for(const origin of config.allowedOrigins){const u=new URL(origin);if(u.origin!==origin||u.username||u.password)throw new Error('Allowed origins must be exact origins without paths or credentials.');if(u.protocol!=='https:'&&!(config.allowLocalhost===true&&u.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(u.hostname)))throw new Error('Use HTTPS, or explicitly allow loopback HTTP for local fixtures.');}
  const seen=new Set();
  for(const app of config.apps){if(!/^[a-z][a-z0-9-]{1,63}$/.test(app.id)||seen.has(app.id))throw new Error('Capture app IDs must be valid and unique.');seen.add(app.id);assertAllowedUrl(app.url,config);if(typeof app.readySelector!=='string'||!app.readySelector.trim())throw new Error('A readySelector is required to prevent blank/loading captures.');if(app.safePreview!==true)throw new Error('Automatic publishing requires a configured safePreview route with approved, sanitized data.');for(const field of ['maskSelectors','rejectSelectors'])if(app[field]!==undefined&&(!Array.isArray(app[field])||app[field].some(x=>typeof x!=='string'||!x)))throw new Error(`${field} must be an array of selectors.`);if(app.authStateEnv&&!/^[A-Z][A-Z0-9_]+$/.test(app.authStateEnv))throw new Error('Invalid auth state environment variable name.');}
  if(config.maxAgeHours!==undefined&&(!Number.isFinite(config.maxAgeHours)||config.maxAgeHours<=0||config.maxAgeHours>8760))throw new Error('maxAgeHours must be between 0 and 8760.');
  return config;
}
export function assertAllowedUrl(value,config){let url;try{url=new URL(value);}catch{throw new Error('Invalid capture URL.');}if(url.username||url.password||!config.allowedOrigins.includes(url.origin))throw new Error('URL is outside the approved capture origins.');if(url.protocol!=='https:'&&!(config.allowLocalhost===true&&url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))throw new Error('Capture URL must use HTTPS.');return url;}
export function usableCapture(record, now=Date.now(), maxAgeHours=168){if(!record||record.approved!==true||!/^screenshots\/[a-z][a-z0-9-]*-[a-f0-9]{12}\.jpg$/.test(record.path||''))return false;const age=now-Date.parse(record.capturedAt);return Number.isFinite(age)&&age>=0&&age<=maxAgeHours*3600000;}
