import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {validateConfig,assertAllowedUrl,usableCapture} from '../capture/policy.mjs';
import {captureOne} from '../capture/worker.mjs';
const app={id:'aim',url:'https://approved.example/aim/preview',readySelector:'[data-thumbnail-ready]',safePreview:true,maskSelectors:['[data-sensitive]']};
const config={allowedOrigins:['https://approved.example'],apps:[app]};
test('reject unapproved origins, credential URLs, and malformed app IDs',()=>{assert.throws(()=>assertAllowedUrl('https://approved.example.evil/aim',config));assert.throws(()=>assertAllowedUrl('https://user:pass@approved.example/',config));assert.throws(()=>validateConfig({...config,apps:[{...app,id:'../aim'}]}));assert.throws(()=>validateConfig({...config,apps:[{...app,safePreview:false}]}));});
test('loopback requires explicit opt-in; origin matching includes port',()=>{assert.throws(()=>validateConfig({allowedOrigins:['http://127.0.0.1:4000'],apps:[]}));assert.doesNotThrow(()=>validateConfig({allowedOrigins:['http://127.0.0.1:4000'],allowLocalhost:true,apps:[]}));assert.throws(()=>assertAllowedUrl('https://approved.example:444/',config));});
test('last known good image is retained only while fresh and approved',()=>{const now=Date.now();const r={path:'screenshots/aim-123456abcdef.jpg',capturedAt:new Date(now-3600000).toISOString(),approved:true,lastAttemptStatus:'failed'};assert.ok(usableCapture(r,now,2));assert.ok(!usableCapture(r,now,.5));assert.ok(!usableCapture({...r,approved:false},now,2));assert.ok(!usableCapture({...r,capturedAt:'bad'},now,2));assert.ok(!usableCapture({...r,path:'https://evil.example/a.jpg'},now,2));});
function mockBrowser({login=false,status=200,url=app.url}={}){const trace={closed:false};const page={setDefaultTimeout(){},async goto(){return {status:()=>status};},url:()=>url,locator(selector){return {selector,async waitFor(){trace.ready=true;},async isVisible(){return login;}};},async evaluate(){},async screenshot(options){trace.screenshot=options;return Buffer.from('MOCK_JPEG_BYTES_FOR_UNIT_TEST_ONLY');}};const context={async route(pattern,handler){trace.route=handler;},async routeWebSocket(){},async newPage(){return page;},async close(){trace.closed=true;}};return {trace,async newContext(options){trace.options=options;return context;}};}
test('capture waits for readiness, masks selectors, writes content-addressed file and closes context (mock browser)',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'dc-capture-'));try{const b=mockBrowser();const result=await captureOne(b,config,app,dir,{});assert.ok(b.trace.ready);assert.deepEqual(b.trace.options.viewport,{width:1440,height:810});assert.equal(b.trace.screenshot.animations,'disabled');assert.equal(b.trace.screenshot.mask[0].selector,'[data-sensitive]');assert.equal(b.trace.closed,true);assert.equal(await readFile(path.join(dir,path.basename(result.path)),'utf8'),'MOCK_JPEG_BYTES_FOR_UNIT_TEST_ONLY');assert.match(result.revision,/^[a-f0-9]{12}$/);let aborted=false;await b.trace.route({request:()=>({url:()=> 'https://not-approved.example'}),abort:async()=>{aborted=true;},continue:async()=>{throw new Error('must not continue');}});assert.ok(aborted);}finally{await rm(dir,{recursive:true,force:true});}});
test('login, error response and redirected disallowed origin never publish a screenshot (mock browser)',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'dc-capture-'));try{for(const scenario of [{login:true},{status:500},{url:'https://evil.example'}]){const b=mockBrowser(scenario);await assert.rejects(captureOne(b,config,app,dir,{}));assert.equal(b.trace.closed,true);assert.equal(b.trace.screenshot,undefined);}assert.equal((await readdir(dir)).length,0);}finally{await rm(dir,{recursive:true,force:true});}});
test('missing required service-account state fails before opening browser',async()=>{await assert.rejects(captureOne(mockBrowser(),config,{...app,authStateEnv:'CAPTURE_AUTH_FILE'},'/tmp/unused',{}),/authentication/);});
